# Generated by Django 4.0.4 on 2022-05-20 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(default='maison', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'categorie',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_publie')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('prix', models.IntegerField()),
                ('Categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caterogie', to='planbamt.categorie')),
                ('image', models.ManyToManyField(blank=True, related_name='plan', to='planbamt.image')),
            ],
            options={
                'verbose_name': 'les Plans de batiment',
                'verbose_name_plural': 'les Plans de batiments',
                'ordering': ['-create_at'],
            },
        ),
    ]
